using System.Text;

namespace SqlVitals.Engine.ConfigChecks;

/// <summary>The outcome of a check. Warnings sort first.</summary>
public enum ConfigCheckStatus
{
    Warn,

    /// <summary>Couldn't be checked here: a permission is missing, or Azure manages the setting.</summary>
    NotChecked,

    Pass,
}

/// <summary>What is checked, in the order the page lists them.</summary>
public enum ConfigCheckKind
{
    MaxDop,
    CostThreshold,
    MaxServerMemory,
    TempDbFileCount,
    TempDbFileSizes,
    AutoShrink,
    PageVerify,
    CompatibilityLevel,
}

/// <summary>
/// One row of the configuration checks (#42): a setting of the server or of a database, its
/// value, the value best practice recommends, and why.
/// </summary>
/// <param name="Scope">"Server", a database's name, or "All 12 databases" for the ones that pass.</param>
/// <param name="FixScript">T-SQL that would bring it to the recommended value, for a warning. Never run by SqlVitals.</param>
public sealed record ConfigCheck(
    ConfigCheckKind   Kind,
    string            Scope,
    ConfigCheckStatus Status,
    string            Current,
    string            Recommended,
    string            Explanation,
    string?           FixScript = null)
{
    public const string ServerScope = "Server";

    public string Name => NameOf(Kind);

    public static string NameOf(ConfigCheckKind kind) => kind switch
    {
        ConfigCheckKind.MaxDop             => "MAXDOP",
        ConfigCheckKind.CostThreshold      => "Cost threshold for parallelism",
        ConfigCheckKind.MaxServerMemory    => "Max server memory",
        ConfigCheckKind.TempDbFileCount    => "TempDB data files",
        ConfigCheckKind.TempDbFileSizes    => "TempDB file sizes",
        ConfigCheckKind.AutoShrink         => "Auto-shrink",
        ConfigCheckKind.PageVerify         => "Page verify",
        ConfigCheckKind.CompatibilityLevel => "Compatibility level",
        _                                  => kind.ToString(),
    };

    /// <summary>Whether it's a database's setting rather than the server's.</summary>
    public bool IsDatabaseCheck => Kind is ConfigCheckKind.AutoShrink or ConfigCheckKind.PageVerify or ConfigCheckKind.CompatibilityLevel;

    public bool IsWarning => Status == ConfigCheckStatus.Warn;

    public string StatusText => Status switch
    {
        ConfigCheckStatus.Warn => "Warn",
        ConfigCheckStatus.Pass => "Pass",
        _                      => "Not checked",
    };
}

/// <summary>The checks for one server, warnings first, or why they couldn't be read.</summary>
/// <param name="Problem">Something that left checks out, or why the list is empty.</param>
public sealed record ConfigCheckList(IReadOnlyList<ConfigCheck> Checks, string? Problem)
{
    /// <summary>False when nothing could be read.</summary>
    public bool Available { get; init; } = true;

    public static ConfigCheckList Unavailable(string problem) => new([], problem) { Available = false };

    public int WarnCount       => Checks.Count(c => c.Status == ConfigCheckStatus.Warn);
    public int PassCount       => Checks.Count(c => c.Status == ConfigCheckStatus.Pass);
    public int NotCheckedCount => Checks.Count(c => c.Status == ConfigCheckStatus.NotChecked);

    /// <summary>Warnings first, then in the order of <see cref="ConfigCheckKind"/>, keeping the order within a kind.</summary>
    public static IReadOnlyList<ConfigCheck> Sort(IEnumerable<ConfigCheck> checks) => checks
        .OrderBy(c => c.IsWarning ? 0 : 1)
        .ThenBy(c => c.Kind)
        .ToList();

    /// <summary>
    /// Every warning's fix in one script, for review. Null when there's nothing to fix. The
    /// server-wide changes take effect at RECONFIGURE; TempDB's new files are used at once.
    /// </summary>
    public string? FixScript(string server, DateTime now) => BuildScript(Checks.Where(c => c.IsWarning), server, now);

    internal static string? BuildScript(IEnumerable<ConfigCheck> checks, string server, DateTime now)
    {
        var fixes = checks.Where(c => c.FixScript is not null).ToList();
        if (fixes.Count == 0)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine($"-- Configuration fixes for {server}, generated by SqlVitals on {now:yyyy-MM-dd HH:mm}.");
        sb.AppendLine("-- Review each change before running it, and run it at a quiet time. SqlVitals does not run this script.");
        foreach (var check in fixes)
        {
            sb.AppendLine();
            sb.AppendLine($"-- {check.Name} ({check.Scope}): {check.Current} → {check.Recommended}");
            sb.AppendLine(check.FixScript!.TrimEnd());
            sb.AppendLine("GO");
        }
        return sb.ToString();
    }
}
